# Generated by Django 4.1.3 on 2022-11-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=50)),
                ('U_Email', models.CharField(max_length=50)),
                ('U_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('P_desc', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Type', models.CharField(max_length=20)),
                ('Offer', models.CharField(max_length=20)),
                ('is_deleted', models.CharField(max_length=5)),
                ('is_Cart', models.CharField(max_length=5)),
                ('Image', models.CharField(max_length=50)),
                ('Order_Confirm', models.CharField(max_length=5)),
                ('uid', models.IntegerField()),
            ],
        ),
    ]
