# Generated by Django 4.1.3 on 2022-11-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uid',
        ),
    ]
