# Generated by Django 4.1.3 on 2022-11-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_remove_product_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='Actual_Price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Order_Confirm',
        ),
        migrations.AddField(
            model_name='product',
            name='Discount_Price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.CharField(max_length=40),
        ),
    ]
