# Generated by Django 4.1.3 on 2022-11-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0003_rename_price_product_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount_Price',
            field=models.CharField(max_length=50),
        ),
    ]
