# Generated by Django 4.1.3 on 2022-11-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0004_alter_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Actual_Price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='Discount_Price',
            field=models.FloatField(),
        ),
    ]
